name: MinecraftDiscordChat
version: 1.0
main: me.therealkeyis.MinecraftPlugin
api-version: 1.19
commands:
  request:
    description: Requests a feature from plugin developer
    usage: /request <feature description>
  link:
    description: Links a minecraft account to a discord account
    usage: /link <discord username>
  voicearea:
    description: Gives user a stick to create a location for a voice chat
    usage: /voicearea <area name>
